### ISSUE TITLE
Hackage Release

### ISSUE THREAD

**Issue by cocreature** [cohomology/gi-cairo-render#1]
Thanks for all the work you’ve put into these two libraries! So far they’ve been working great for me!
I was wondering if you have thought about putting these libs on Hackage to make them easier to use. If there are any specific blockers that you want to address before that, I’m happy to see if I can find some time to contribute.

**Comment by Magicloud** [comment]
Yes, please. I use these two packages in a dyre package (which is not easy going with stack), so this works in hackage is quite important if I release the change.

**Comment by barryfm** [comment]
I've been using these two packages with stack lts-12.23 (ghc-8.4.4) and with NixOS ghc-8.6.3 without issues, to support Chart based  plots with gtk3 and file outputs.  It would be nice to see it in Hackage and Stack.  I think it would be useful in supporting a more general move from gtk2hs to haskell-gi in a variety of packages.

**Comment by IvanMalison** [comment]
@cohomology Any word on this?

**Comment by IvanMalison** [comment]
I'd like to switch https://github.com/taffybar/taffybar and https://github.com/taffybar/gtk-sni-tray over to this to avoid gtk2hs-buildtools, but I need stuff to be in hackage so that cabal builds work.

**Comment by IvanMalison** [comment]
@cohomology I ended up releasing this on hackage a while ago. Now we need to make some changes to ensure compatibility with newer version of haskell-gi, so I'm going to fork this repo to taffybar and point the hackage version there. If you ever want to reclaim the official source of the package, just let me know and i'll point it back.

**Comment by cohomology** [comment]
Hi Malison,

no problem.

Best regards,
Kilian.

**Comment by SolarAquarion** [comment]
@IvanMalison I'm trying to package this on Arch, but the fact that this doesn't have a way to properly package it on Arch is annoying

**Comment by IvanMalison** [comment]
@SolarAquarion I'm not sure what you mean. Also, I generally think that packaging things for arch just isnt a great idea. Just use cabal/stack/nix to install.

**Comment by SolarAquarion** [comment]
I'm trying to build taffybar via stack and its failing at gi-pango

**Comment by barryfm** [comment]
Which stack release are you trying?  I have had problems starting with lts-13.25 where only a partial update of the gi-* packages was done.  This is a known bug (I think specific to Gnome 3.32) fixed in the nightly builds, but was not applied to lts-13 because it would require a major release change to haskell-gi, not permitted by LTS rules.  There is a upcoming lts-14 release which I hope resolved the problem.   I build (using system-ghc: false and the new stack-2) nightly-2019-07-14 and nightly-2019-07-20 using gi-cairo-render and gi-gtk-hs in my own apps without problems.

**Comment by SolarAquarion** [comment]
Its the thing I posted in the gitter
