### ISSUE TITLE
Type Surface is not the same one in gi-cairo.

### ISSUE THREAD

**Issue by Magicloud** [cohomology/gi-cairo-render#2]
Context works in both libs, but Surface does not. Wondering why gi-cairo-render defined Surface itself.

**Comment by cohomology** [comment]
What do you mean by that? ... I used Surface in, e.g. hlabyrinth (see examples). It works. Do you have some specific example ... ?

**Comment by Magicloud** [comment]
It was such a long time ago.... As I recalled, some types are defined twice in gi-cairo and gi-cairo-render back then. But I do not know if anything was updated since.

**Comment by Magicloud** [comment]
I think I will close this for now until I met the same problem.
