### ISSUE TITLE
Import into haskell-gi repo?

### ISSUE THREAD

**Issue by garetxe** [cohomology/gi-cairo-render#7]
Hi!

I have an outstanding pull request in `haskell-gi` adding bindings for `libsrvg`. The PR includes an example program using `gi-cairo-render`, but unfortunately this breaks CI due to https://github.com/cohomology/gi-cairo-render/issues/6 .

It would be great if you could fix that whenever you have a sec (so I can merge the full PR), but I understand if you are busy, so I wanted to ask about a more general point instead: `gi-cairo-render` is clearly a good idea, and I would be happy to do the work to keep it working as `haskell-gi` evolves, whenever I need to bump versions or change internal interfaces. So I was wondering: would you be interested in merging this repo into the `haskell-gi` repo, so I can fix things as needed? We already include `gi-gtk-hs` inside the repo for the same reason.

Thanks!

**Comment by cohomology** [comment]
Hi Iñaki,

sorry, I am very busy at the moment ... but the idea is great. Let's just merge it.

How to we proceed? Upload a new hackage version with new source-repo? Can you do it yourself or do you need me?

Best regards,
Kilian.

**Comment by podiki** [comment]
Just wanted to check in on this, if it would resolve gi-cairo-render and -connector (along with dependents like @taffybar) being droped from stackage: commercialhaskell/stackage@de4c3e6

**Comment by colonelpanic8** [comment]
@podiki It definitely eventually would lead to that.

**Comment by garetxe** [comment]
Thanks Kilian!

I have just merged the gi-cairo-render repo into haskell-gi (and also hlabyrinth). Everything seems to work, at least the CI passes and hlabyrinth works (it's fun, by the way :) ). I think that you have write access to the haskell-gi repo already, but please let me know if you don't.

I would be happy to upload a new version of `gi-cairo-render` and `gi-cairo-connector` to hackage if you give me permissions.

**Comment by garetxe** [comment]
@cohomology I am now in the process of releasing new versions of `haskell-gi`, `haskell-gi-base` and the bindings. Could I get permissions to upload the updated `gi-cairo-render` and `gi-cairo-connector` to hackage, to go with the new `haskell-gi` versions? My hackage username in `inaki`. Thank you very much in advance!

**Comment by cohomology** [comment]
Hi Inaki,

sorry I am very busy at the moment. I gave you permissions to upload gi-cairo-connector and gi-cairo-render.

Best regards,
Kilian.

**Comment by garetxe** [comment]
Great, thanks a lot! I have just uploaded new versions with the updated dependency bounds.
